dbt_nyc:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: db
      # host: localhost
      port: 5432
      user: root
      pass: root
      dbname: nyc
      schema: target
